#ifndef ADDRESSES_H
#define ADDRESSES_H
#include <string>

#define ADDR_PLACEHOLDER 0x01234567

//PLAYER
#define ADDR_CJHEALTH 0x0
#define ADDR_CJARMOR 0x0
#define ADDR_CJOXYGEN 0x0
#define ADDR_CJMONEY 0x0

//STATS
#define ADDR_CJFAT 0x0
#define ADDR_CJSTAMINA 0x0
#define ADDR_CJMUSCLE 0x0
#define ADDR_CJSEXAPPEAL 0x0

//TIME
#define ADDR_HOUR 0x0
#define ADDR_MIN 0x0
#define ADDR_TIMEFREEZE1 0x0
#define ADDR_TIMEFREEZE2 0x0

//SHADER
#define ADDR_DRAWDISTANCE 0x0
#define ADDR_BRIGHTNESS 0x0
#define ADDR_SATURATION 0x0

//PHYSICS
#define ADDR_GRAVITY 0x0

//MISC
#define ADDR_CHEATROMEROID 0x0
#define ADDR_CHEATHYDRAID 0x0
#define ADDR_CHEATHUNTERID 0x0
#define ADDR_VEHICLEBOOST 0x0

#endif // ADDRESSES_H
